export {default as Hero} from "./Hero"
export {default as About} from "./About"
export {default as Service} from "./Service"
export {default as Project} from "./Project"
export {default as Skills} from "./Skills"
export {default as Footer} from "./Footer"